# Generated by Django 4.0.2 on 2022-02-07 02:04

import api.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='schedule name', max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]*$', 'only english characters, numbers, - and _ are allowed allowed.')], verbose_name='schedule name')),
                ('user', models.ForeignKey(help_text='user for this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='meet name', max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]*$', 'only english characters, numbers, - and _ are allowed allowed.')], verbose_name='meet name')),
                ('url', models.URLField(help_text='meet url', verbose_name='url')),
                ('start_datetime', models.DateTimeField(help_text="current week's start datetime for this meet in format %Y-%m-%d %H:%M:%S", validators=[api.validators.datetime_in_current_week_validator], verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(help_text="current week's end datetime for this meet in format %Y-%m-%d %H:%M:%S", validators=[api.validators.datetime_in_current_week_validator], verbose_name='end datetime')),
                ('schedule', models.ForeignKey(help_text='schedule for this meet', on_delete=django.db.models.deletion.CASCADE, related_name='meets', to='api.schedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'meet',
                'verbose_name_plural': 'meets',
                'ordering': ['start_datetime'],
            },
        ),
    ]
